name: build rpifancon

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v main/rpifancon.go

    - name: Build
      run: GOOS=linux GOARCH=arm64 go build -v main/rpifancon.go
